networks:
  hasher-network:
    internal: true
  redis-network:
    internal: true
  rng-network:
    internal: true
  webui-init-network:
    internal: false

secrets:
  hasher-secret:
    file: ./hasher/hasher.rb
  rng-secret:
    file: ./rng/rng.py
  webui-secret:
    file: ./webui/webui.js
  worker-secret:
    file: ./worker/worker.py
  
services:
  hasher:
    command: 
      - hasher.rb
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 2
      resources:
        limits:
          cpus: '0.010'
          memory: 100M
        reservations:
          cpus: '0.010'
          memory: 20M
    entrypoint: /usr/local/bin/ruby
    environment:
      HELLO: world
      AUTHOR: Sebastian
    expose:
      - 8080
    image: academiaonline/simplilearn-dockercoins:test-hasher
    networks:
      - hasher-network
    read_only: true
    secrets:
      -
        gid: '1000620000'
        mode: 0400
        source: hasher-secret
        target: /app/hasher.rb
        uid: '1000620000'
    user: '1000620000'
    working_dir: /app/
  
  redis:
    command: 
      - redis-server
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: '0.010'
          memory: 100M
        reservations:
          cpus: '0.010'
          memory: 20M
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    environment:
      HELLO: world
      AUTHOR: Sebastian
    expose:
      - 6379
    image: library/redis:alpine
    networks:
      - redis-network
    read_only: true
    user: 'redis:redis'
    volumes:
      - redis-volume:/data/:rw
    working_dir: /data/
  
  rng:
    command: 
      - rng.py
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 2
      resources:
        limits:
          cpus: '0.010'
          memory: 100M
        reservations:
          cpus: '0.010'
          memory: 20M
    entrypoint: /usr/local/bin/python
    environment:
      HELLO: world
      AUTHOR: Sebastian
    expose:
      - 8080
    image: academiaonline/simplilearn-dockercoins:test-rng
    networks:
      - rng-network
    read_only: true
    secrets:
      -
        gid: '1000620000'
        mode: 0400
        source: rng-secret
        target: /app/rng.py
        uid: '1000620000'
    user: '1000620000:1000620000'
    working_dir: /app/
  
  webui:
    command: 
      - webui.js
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 2
      resources:
        limits:
          cpus: '0.010'
          memory: 100M
        reservations:
          cpus: '0.010'
          memory: 20M
    entrypoint: /usr/local/bin/node
    environment:
      HELLO: world
      AUTHOR: Sebastian
    expose:
      - 8080
    image: academiaonline/simplilearn-dockercoins:test-webui
    networks:
      - redis-network
    ports:
      - 80:8080
    read_only: true
    secrets:
      -
        gid: '1000620000'
        mode: 0400
        source: webui-secret
        target: /app/webui.js
        uid: '1000620000'
    user: '1000620000:1000620000'
    volumes:
      - webui-volume:/app/files/:ro
    working_dir: /app/
  webui-init:
    command:
      - -c
      - rm -rf simplilearn-dockercoins/ && git clone https://github.com/academiaonline/simplilearn-dockercoins && cd simplilearn-dockercoins/ && git checkout 2021-08 && cp -rf webui/files/* /shared/ && sleep infinity
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.010'
          memory: 100M
        reservations:
          cpus: '0.010'
          memory: 20M
    entrypoint: /bin/sh
    environment:
      HELLO: bye
    image: alpine/git:latest
    networks:
      - webui-init-network
    read_only: true
    user: root
    volumes:
      - webui-init-volume:/init/:rw
      - webui-volume:/shared/:rw
    working_dir: /init/
  
  worker:
    command: 
      - worker.py
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 2
      resources:
        limits:
          cpus: '0.010'
          memory: 100M
        reservations:
          cpus: '0.010'
          memory: 20M
    entrypoint: /usr/local/bin/python
    environment:
      HELLO: world
      AUTHOR: Sebastian
    image: academiaonline/simplilearn-dockercoins:test-worker
    networks:
      - hasher-network
      - redis-network
      - rng-network
    read_only: true
    secrets:
      -
        gid: '1000620000'
        mode: 0400
        source: worker-secret
        target: /app/worker.py
        uid: '1000620000'
    user: '1000620000:1000620000'
    working_dir: /app/

version: '3.8'

volumes:
  redis-volume:
  webui-init-volume:
  webui-volume:
