apiVersion: v1
kind: ReplicationController
metadata:
  name: webui-rc
spec:
  replicas: 2
  selector:
    webui-key: webui-value
  template:
    metadata:
      labels:
        webui-key: webui-value
    spec:
      containers:
        -
          args:
            - webui.js
          command:
            - /usr/local/bin/node
          env:
            - 
              name: HELLO
              value: world
            - 
              name: AUTHOR
              value: Sebastian
          image: academiaonline/simplilearn-dockercoins:webui-test
          name: webui-container
          ports:
            - 
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 10m
              memory: 100M
            requests:
              cpu: 10m
              memory: 20M
          securityContext:
            runAsGroup: 1000620000
            runAsUser: 1000620000
          volumeMounts:
            -
              mountPath: /app/webui.js
              name: webui-volume
              readOnly: true
              subPath: webui.js
            -
              mountPath: /app/files/
              name: webui-files-volume
              readOnly: true
          workingDir: /app/
      initContainers:
        -
          args:
            - -c
            - rm -rf simplilearn-dockercoins/ && git clone https://github.com/academiaonline/simplilearn-dockercoins && cd simplilearn-dockercoins/ && git checkout 2021-08 && cp -rf webui/files/* /shared/
          command:
            - /bin/sh
          env:
            - 
              name: HELLO
              value: bye
          image: alpine/git:latest
          name: webui-init-container
          resources:
            limits:
              cpu: 10m
              memory: 100M
            requests:
              cpu: 10m
              memory: 20M
          volumeMounts:
            -
              mountPath: /shared/
              name: webui-files-volume
              readOnly: false
            -
              mountPath: /init/
              name: webui-init-volume
              readOnly: false
          workingDir: /init/
      volumes:
        -
          name: webui-volume
          secret:
            secretName: webui-secret
        -
          name: webui-files-volume
          emptyDir: {}
        -
          name: webui-init-volume
          emptyDir: {}
          
