apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  ports:
    -
      nodePort: 30000
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    webui: "true"
  type: NodePort
